DEFAULT_SEED = 777
UNIT_COST = True
SHARED_TIMERS = True

SAMPLING_MAX_SAMPLES = 25000
SAMPLING_MAX_TIME = 15 * 60  # seconds
TRAIN_MAX_TIME = 10 * 60  # seconds
TEST_MAX_SEARCH_TIME = 30 * 60  # seconds
SAMPLING_MEM_LIMIT_MB = int(7.5 * 1024)  # MB
TRAIN_MAX_MEMORY = int(7.5 * 1024)  # MB
TEST_MAX_SEARCH_MEMORY = int(8 * 1024)  # MB

SAMPLING_TECHNIQUE = "bfs_rw"  # ['rw', 'dfs', 'bfs', 'bfs_rw']
SAMPLING_SEARCHES = -1
SAMPLING_PER_SEARCH = -1
SAMPLING_STATE_FILTERING = "mutex"  # ['none', 'mutex']
SAMPLING_ALLOW_DUPLICATES = "interrollout"  # ['all', 'interrollout', 'none']
SAMPLING_REGRESSION_DEPTH = (
    "facts_per_avg_effects"  # [int, 'default', 'facts', 'facts_per_avg_effects']
)
SAMPLING_RESTART_H_WHEN_GOAL_STATE = "true"
SAMPLING_BFS_PERCENTAGE = 0.1  # [0.0 .. 1.0]
SAMPLING_RANDOM_PERCENTAGE = 0.2  # [0.0 .. 1.0]
SAMPLING_SAI = "both"  # ['none', 'partial', 'complete', 'both']
SAMPLING_SUI = "true"

TRAIN_MODEL = "resnet"
TRAIN_NUM_FOLDS = 1
TRAIN_HIDDEN_LAYERS = 2
TRAIN_HIDDEN_UNITS = [250]
TRAIN_BATCH_SIZE = 512
TRAIN_BIAS = True
TRAIN_WEIGHTS_METHOD = "kaiming_uniform"
TRAIN_OUTPUT_LAYER = "regression"
TRAIN_LINEAR_OUTPUT = False
TRAIN_NORMALIZE_OUTPUT = False
TRAIN_ACTIVATION = "relu"
TRAIN_LOSS_FUNCTION = "mse"
TRAIN_WEIGHT_DECAY = 0
TRAIN_DROPOUT_RATE = 0
TRAIN_LEARNING_RATE = 0.0001
TRAIN_PATIENCE = 25
TRAIN_SHUFFLE = True
TRAIN_TRAINING_SIZE = 0.9
TRAIN_MAX_EPOCHS = 2**20  # infinite
TRAIN_RESTART_NO_CONV = True
TRAIN_CHECK_DEAD_ONCE = True
TRAIN_SEED_INCREMENT_WHEN_BORN_DEAD = 100
TRAIN_SAVE_BEST_EPOCH_MODEL = True
TRAIN_OUTPUT_FOLDER = "results"
TRAIN_USE_GPU = False

TEST_DOMAIN_PDDL = ""
TEST_PLAN_FILE = ""
TEST_SEARCH_ALGORITHM = "eager_greedy"  # ['astar', 'eager_greedy']
TEST_HEURISTIC = "nn"
TEST_HEURISTIC_MULTIPLIER = 1
TEST_TEST_MODEL = "all"
TEST_MAX_EXPANSIONS = float("inf")
TEST_SAVE_DOWNWARD_LOGS = True
